-- Supabase Database Schema for Photo Blog
--
-- This project uses a hybrid approach:
-- - Supabase: Authentication (magic links) ONLY
-- - Directus: Content management (albums, photos, memberships)
--
-- NO DATABASE TABLES NEEDED IN SUPABASE!
--
-- Supabase is used only for its auth.users table (managed automatically)
-- and for sending magic link emails.
--
-- All membership data is stored in Directus CMS.
-- See DIRECTUS_SETUP.md for creating the memberships collection.

-- Nothing to run here!
-- Supabase Auth tables are created automatically.
-- Just use Supabase for authentication API.
